# Generated by Django 4.2.7 on 2023-11-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='endusers',
            options={'verbose_name': 'End Users', 'verbose_name_plural': 'End Users'},
        ),
    ]
